 name: DiscordBridge
 version: 1.3.1
 description: Plugin to bridge discord and Minecraft
 author: PintTheDragon
 
 main: com.PintTheDragon.DiscordBridge.DiscordBridge

 softdepend: [PlaceholderAPI, Vault, EssentialsX]
 
 commands:
   setplayer:
     description: Sets your discord to your minecraft account
     usage: /setplayer &lt;Discord ID&gt;
   disbreload:
     description: Reloads the plugin
     usage: /disbreload
     permission: discordbridge.reload
   disbreconnect:
     description: Attempts to reconnect to the bot
     usage: /disbreconnect
     permission: discordbridge.reload
   disbsetup:
     description: Used to setup the server
     permission: discordbridge.setup

 permissions:
   discordbridge.*:
     description: Full permission to all DiscordBridge commands
     children:
       discordbridge.reload: true
       discordbridge.setup: true
   discordbridge.reload:
     description: Allows you to reload/reconnect the plugin
     default: op
   discordbridge.setup:
     description: Used to setup the server
     default: op